### ISSUE TITLE
Add workflow for creating a new release branch

### ISSUE THREAD

**Issue by dkliban** [pulp/plugin_template#417]
The new workflow should triggered manually from master branch. It needs to take a name parameter. The workflow needs to check that the branch name matches up with the current version on master branch. If the name of the branch and the X.Y portion of the version string match, the workflow should create a new branch that is exactly like master and then bump the version on master and open a PR with that version bump.

**Comment by mdellweg** [comment]
Should the release branch not be a side effect of the release workflow when run for a minor release?
Do we need an extra workflow?

**Comment by daviddavis** [comment]
Having a separate workflow would allow us to branch independently from releasing. Perhaps if we want to merge a commits to master that we don't want to release in the next y-release (but aren't ready to release that yet).

Also, as the current release workflow stands, you release a branch (and not a commit) so if people are merging to master, there's no guarantee which commit gets branched/released. We could add a field though to specify a specific commit.

**Comment by mdellweg** [comment]
So you are saying we might branch a week before releasing without holding the development on master.
That sounds like an implementation of a "feature freeze". That actually sounds really good.
