### ISSUE TITLE
Changelogs for bugfix releases are not immediately published

### ISSUE THREAD

**Issue by mdellweg** [pulp/plugin_template#523]
This is a transformation of https://pulp.plan.io/issues/9361

**Comment by quba42** [comment]
Maybe there should be a separate workflow for releasing documentation? In some cases it might be desirable to update documentation right away (without updating anything else).

**Comment by mdellweg** [comment]
> Maybe there should be a separate workflow for releasing documentation? In some cases it might be desirable to update documentation right away (without updating anything else).

That's what the PR tries to accomplish. (Maybe it does... hard to test pre merge.)
