### ISSUE TITLE
Changing the name of a branch does not result in updating the stage changelog workflow

### ISSUE THREAD

**Issue by lubosmj** [pulp/plugin_template#526]
When I change the name of a branch in template_config.yml, one of the workflows should be updated as well:

```diff
 plugin_caps_short: OSTREE
 plugin_dash: pulp-ostree
 plugin_dash_short: ostree
-plugin_default_branch: master
+plugin_default_branch: main
 plugin_name: pulp_ostree
 plugin_snake: pulp_ostree
 post_job_template: null
```

```diff
       - name: Cleanup repository before making changelog PR
         run: rm -rf .lock generation pulp_ostree_client* *-client.tar pulp_ostree.tar todo web docs.tar
 
-      - name: Stage changelog for master branch
-        run: python .github/workflows/scripts/stage-changelog-for-master.py ${{ github.event.inputs.release }}
+      - name: Stage changelog for main branch
+        run: python .github/workflows/scripts/stage-changelog-for-main.py ${{ github.event.inputs.release }}
 
       - name: Create Pull Request for Changelog
         uses: peter-evans/create-pull-request@v3

```

```diff
 
 helper = textwrap.dedent(
     """\
-        Stage the changelog for a release on master branch.
+        Stage the changelog for a release on main branch.
 
         Example:
-            $ python .github/workflows/scripts/stage-changelog-for-master.py 3.4.0
+            $ python .github/workflows/scripts/stage-changelog-for-main.py 3.4.0
 
     """
 )
```

**Comment by lubosmj** [comment]
In the files `templates/github/.github/workflows/release.yml.j2` and `templates/github/.github/workflows/scripts/stage-changelog-for-master.py.j2`, there should be used the `{{ plugin_default_branch }}` placeholders instead of pure `master`. Furthermore, the latter file should be named based on the default branch name.

**Comment by mdellweg** [comment]
stage-changelog-for-master.py.j2 `...for_default_branch.py.j2` would be an agnostic name...

**Comment by quba42** [comment]
Probably a good idea to run `git grep master` in the plugin template repo, to see what else crops up.

**Comment by lubosmj** [comment]
@mdellweg, what is a proper way of renaming this file with respect to the plugin template regeneration? Can I simply rename it and do not care about the original file that will not be removed in current plugins automatically?

**Comment by mdellweg** [comment]
There is a list of deprecated filenames, and you are advided to delete them. I don't think we do automatically.
