### ISSUE TITLE
release script generates the wrong issue URLs in the changelog

### ISSUE THREAD

**Issue by dkliban** [pulp/plugin_template#560]
537 below refers to a github issue and not a pulp.plan.io issue. The script needs to use the right issue tracker.

```
Bugfixes
--------

- Fixed "manifest_id" violates not-null constraint error during sync.
  `#537 <https://pulp.plan.io/issues/537>`_
```

**Comment by fao89** [comment]
you need to update `pyproject.toml` of your plugin:
https://github.com/pulp/pulp_ansible/blob/main/pyproject.toml#L14

**Comment by fao89** [comment]
https://github.com/pulp/pulp_container/blob/2.8/pyproject.toml#L14

vs

https://github.com/pulp/pulp_container/blob/main/pyproject.toml#L14

**Comment by dkliban** [comment]
@fao89 thank you. i'll close this issue.
