### ISSUE TITLE
Cherry-pick automation does not work when merge commits are used

### ISSUE THREAD

**Issue by quba42** [pulp/plugin_template#619]
It looks like when using the patchback cherry-pick automation, the merge commit will be cherry picked.

Since the merge commit does not contain the issue reference in the commit message, the so opened PR will then fail the commit message validation as follows: https://github.com/pulp/pulp_deb/pull/483

* One possible solution is to change the pulp_deb repo settings to stop using merge commits (and use manual cherry-picks until then).
* Another possibility would be to always add the issue reference in the merge commit message going forwards.
* The final option would be to have the automation cherry-pick not the merge commit, but the individual commits on the PR being backported.

**Comment by fao89** [comment]
> It looks like when using the patchback cherry-pick automation, the merge commit will be cherry picked.
> 
> Since the merge commit does not contain the issue reference in the commit message, the so opened PR will then fail the commit message validation as follows: [pulp/pulp_deb#483](https://github.com/pulp/pulp_deb/pull/483)
> 
> * One possible solution is to change the pulp_deb repo settings to stop using merge commits (and use manual cherry-picks until then).

I think this is the easier solution
> * Another possibility would be to always add the issue reference in the merge commit message going forwards.

I don't know how to configure the merge commit messages
> * The final option would be to have the automation cherry-pick not the merge commit, but the individual commits on the PR being backported.

this would probably be a new patchback feature https://github.com/sanitizers/patchback-github-app/issues
