### ISSUE TITLE
update labels is using plugin_snake

### ISSUE THREAD

**Issue by mdellweg** [pulp/plugin_template#788]
This does not produce propoer repository names.

**Comment by MichalPysik** [comment]
@mdellweg Can you please specify example(s) when the repository name is incorrect?

I know plugins like file, rpm, etc. use snake case, while for example pulp-cli doesn't, but I guess that repository does not have backport labels at all.

**Comment by mdellweg** [comment]
pulp-certguard

https://github.com/pulp/pulp-certguard/actions/workflows/update-labels.yml
