### ISSUE TITLE
support for ruby 2.6 seems to be dropped

### ISSUE THREAD

**Issue by dosas** [pulp/plugin_template#812]
It seems like support for ruby 2.6 was dropped by [setup-ruby](https://github.com/ruby/setup-ruby)

[see](https://github.com/pulp/pulp-openapi-generator/actions/runs/6954699735/job/19100113958?pr=86)

```
Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.6 not found
```

Does this require adaptations in
* https://github.com/pulp/plugin_template/blob/main/templates/macros.j2#L46
* https://github.com/pulp/plugin_template/blob/main/templates/macros.j2#L46

This is a strange error since the version is in the list of [supported versions](https://github.com/ruby/setup-ruby/blob/master/ruby-builder-versions.json)

**Comment by dosas** [comment]
@mdellweg Thank you for the hint. In that case it is not a problem of this repository but only of [pulp-openapi-generator]
(https://github.com/pulp/pulp-openapi-generator/blob/main/.github/workflows/ci.yml#L56)

**Comment by mdellweg** [comment]
It is still a non maintained action, right? We should consider replacing it.

**Comment by dosas** [comment]
AFAIK it is already replaced for [plugin_template](https://github.com/pulp/plugin_template/blob/main/templates/macros.j2#L46). I made a [PR](https://github.com/pulp/pulp-openapi-generator/pull/88) for pulp-openapi-generator
