### ISSUE TITLE
update_core_lowerbound can fail in the presence of an X.Y.Z-lowerbound-specifier

### ISSUE THREAD

**Issue by ggainey** [pulp/plugin_template#895]
pulp_rpm currently specifies a very specific pulpcore lowerbound due to needing a specific bugfix - see https://github.com/pulp/pulp_rpm/blob/main/requirements.txt#L6 , where we call out needing pulpcore>=3.49.11

This check https://github.com/pulp/plugin_template/blob/bd7ee18268acd0b676670fbc595511f75e479d08/scripts/update_core_lowerbound.py#L31C1-L31C66 looks like it's failing to recognize 3.49.11 as a supported branch, and therefore our CI-update is failing with https://github.com/pulp/pulp_rpm/actions/runs/9942408703/job/27538226968#step:7:106

We think this check needs to specifically compare **just** core/x.y with plugin-spec core/x.y

**Comment by pedro-psb** [comment]
Closed by https://github.com/pulp/plugin_template/pull/896
